artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Nexaaman/Event_Page/raw/main/Dataset.zip
  local_path: artifacts/data_ingestion/Dataset.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  status: artifacts/data_validation/status.txt
  REQUIRED_FILES: ["train", "test", "validation"]


data_tranformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Dataset
  tokenizer: openai-community/gpt2
  model: openai-community/gpt2


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/Dataset
  model: openai-community/gpt2
  tokenizer: openai-community/gpt2